name: domain
description: A new Flutter package project.
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  uuid: ^3.0.1
  
dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


